/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.kigawa.keruta.executor.client.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique identifier for the repository
 * @param name Repository name
 * @param url Repository URL
 * @param createdAt Repository creation timestamp
 */


data class Repository (

    /* Unique identifier for the repository */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Repository name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Repository URL */
    @Json(name = "url")
    val url: kotlin.String? = null,

    /* Repository creation timestamp */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

)

