/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.kigawa.keruta.executor.client.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Repository name
 * @param url Repository URL
 */


data class RepositoryCreateRequest (

    /* Repository name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Repository URL */
    @Json(name = "url")
    val url: kotlin.String

)

