/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.kigawa.keruta.executor.client.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Updated session name
 * @param description Updated session description
 * @param repositoryUrl Updated Git repository URL
 * @param repositoryRef Updated Git repository reference (branch, tag, or commit)
 * @param tags Updated tags for the session
 */


data class SessionUpdateRequest (

    /* Updated session name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Updated session description */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Updated Git repository URL */
    @Json(name = "repositoryUrl")
    val repositoryUrl: kotlin.String? = null,

    /* Updated Git repository reference (branch, tag, or commit) */
    @Json(name = "repositoryRef")
    val repositoryRef: kotlin.String? = null,

    /* Updated tags for the session */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

)

