/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.kigawa.keruta.executor.client.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Session name
 * @param tags Initial tags for the session
 */


data class SessionCreateRequest (

    /* Session name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Initial tags for the session */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

)

