/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.kigawa.keruta.executor.client.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique identifier for the session
 * @param name Session name
 * @param status Current status of the session
 * @param createdAt Session creation timestamp
 * @param updatedAt Session last update timestamp
 * @param tags Tags associated with the session
 */


data class Session (

    /* Unique identifier for the session */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Session name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Current status of the session */
    @Json(name = "status")
    val status: Session.Status? = null,

    /* Session creation timestamp */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    /* Session last update timestamp */
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null,

    /* Tags associated with the session */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * Current status of the session
     *
     * Values: pENDING,rUNNING,cOMPLETED,fAILED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "PENDING") pENDING("PENDING"),
        @Json(name = "RUNNING") rUNNING("RUNNING"),
        @Json(name = "COMPLETED") cOMPLETED("COMPLETED"),
        @Json(name = "FAILED") fAILED("FAILED");
    }
}

