/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.kigawa.keruta.executor.client.api

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import net.kigawa.keruta.executor.client.model.GetHealth200Response

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import net.kigawa.keruta.executor.client.infrastructure.ApiClient
import net.kigawa.keruta.executor.client.infrastructure.ApiResponse
import net.kigawa.keruta.executor.client.infrastructure.ClientException
import net.kigawa.keruta.executor.client.infrastructure.ClientError
import net.kigawa.keruta.executor.client.infrastructure.ServerException
import net.kigawa.keruta.executor.client.infrastructure.ServerError
import net.kigawa.keruta.executor.client.infrastructure.MultiValueMap
import net.kigawa.keruta.executor.client.infrastructure.PartConfig
import net.kigawa.keruta.executor.client.infrastructure.RequestConfig
import net.kigawa.keruta.executor.client.infrastructure.RequestMethod
import net.kigawa.keruta.executor.client.infrastructure.ResponseType
import net.kigawa.keruta.executor.client.infrastructure.Success
import net.kigawa.keruta.executor.client.infrastructure.toMultiValue

class HealthApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:8080")
        }
    }

    /**
     * Health check
     * Returns the health status of the application
     * @return GetHealth200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getHealth() : GetHealth200Response = withContext(Dispatchers.IO) {
        val localVarResponse = getHealthWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetHealth200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Health check
     * Returns the health status of the application
     * @return ApiResponse<GetHealth200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getHealthWithHttpInfo() : ApiResponse<GetHealth200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getHealthRequestConfig()

        return@withContext request<Unit, GetHealth200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getHealth
     *
     * @return RequestConfig
     */
    fun getHealthRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/health",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
